### recuperar todas las alertas pendientes
GET http://localhost:3000/api/alerts/?term=1

#### guardar/actualizar una alerta

POST http://localhost:3000/api/alerts/?term=3
Content-Type: application/json

{
  "id": null,
  "titulo": "Falta disponibilidad horaria para Jose Perez",
  "estado": "IGNORADA",
  "fecha": null,
  "motivoCambio": "prueba endpoint crear alerta"
}