### recuperar todos los prerrequisitos de un término
GET http://localhost:3000/api/prerequitos?term=2

### recuperar los prerrequisitos de una materia específica en un término
GET http://localhost:3000/api/prerequitos?term=2&materia=INF-301

### guardar un prerrequisito
POST http://localhost:3000/api/prerequitos
Content-Type: application/json

{
    "codigoAsignatura": "INF-301",
    "codigoTermAsignatura": "2",
    "codigoAsignaturaPrerequito": "INF-202",
    "codigoTermPrerequito": "2"
}

### eliminar un prerrequisito
DELETE http://localhost:3000/api/prerequitos
Content-Type: application/json

{
    "codigoAsignatura": "INF-301",
    "codigoTermAsignatura": "2",
    "codigoAsignaturaPrerequito": "INF-202",
    "codigoTermPrerequito": "2"
}
